services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET: ${DJANGO_SECRET}

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432

      NEO_URI: bolt://neo4j:7687
      NEO_USER: ${NEO_USER}
      NEO_PASSWORD: ${NEO_PASSWORD}

      HF_HOME: /cache/hf
      TRANSFORMERS_CACHE: /cache/hf
    volumes:
      - .:/app
      - hf_cache:/cache/hf
    depends_on:
      - postgres
      - neo4j

  postgres:
    image: postgres:18-bookworm
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  neo4j:
    image: neo4j:5.26.23-community-ubi10
    environment:
      NEO4J_AUTH: ${NEO_USER}/${NEO_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
  hf_cache:
