# Generated by Django 5.2.12 on 2026-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicrequest",
            name="source_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
